# Dockerfile.testing
FROM node:18.17.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json or yarn.lock
COPY package*.json ./

# Install dependencies including 'devDependencies'
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .


