name: Docker Build and Push

on:
  push:
    branches:
      - feature/blackBox

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker build -t krud3/desarrollo2:latest .
          docker push krud3/desarrollo2:latest
