name: Docker Build and Push

on:
  push:
    branches:
      - feature/blackBox

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME2 }}
          password: ${{ secrets.DOCKER_PASSWORD2 }}

      - name: Build and push Docker image
        run: |
          docker build -t front/desarrollo2:latest .
          docker push front/desarrollo2:latest
