on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - feature/blackBox
  pull_request:
    branches:
      - feature/blackBox

name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2 
      with:
        args: >
          -Dsonar.organization=desarrollo2front
          -Dsonar.projectKey=Krud3_proyectoDesarrollo2-FrontEnd
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**
          -Dsonar.language=js
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm run build
          npx sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}